import type { Language } from "./LanguageContext";

export type LegalSection = {
  heading: string;
  paragraphs: string[];
  list?: string[];
};

export type LegalCopy = {
  metaTitle: string;
  metaDescription: string;
  kicker: string;
  title: string;
  updated: string;
  intro: string;
  sections: LegalSection[];
  back: string;
  contactLabel: string;
};

export const privacyPolicy: Record<Language, LegalCopy> = {
  en: {
    metaTitle: "Privacy Policy | Colosson",
    metaDescription:
      "How Colosson collects, uses and protects personal data under Colombian data protection law (Law 1581 of 2012 and Decree 1074 of 2015).",
    kicker: "Legal · Data protection",
    title: "Privacy policy",
    updated: "Last updated: September 3, 2026",
    intro:
      "This policy explains how Colosson S.A.S. (“Colosson”, “we”) collects, uses, stores and protects the personal data of visitors, clients and prospects, in accordance with Colombian Law 1581 of 2012, Decree 1074 of 2015 (Title 2, Chapter 25) and the guidance of the Superintendencia de Industria y Comercio (SIC), the Colombian data protection authority.",
    sections: [
      {
        heading: "1. Who is responsible for your data",
        paragraphs: [
          "Colosson S.A.S., based in Medellín, Antioquia, Colombia, is the data controller (“Responsable del Tratamiento”) for the personal data collected through colosson.net and our commercial channels.",
          "Contact: ventas@colosson.co · +57 317 089 3000 · Medellín, Colombia.",
        ],
      },
      {
        heading: "2. Data we collect",
        paragraphs: [
          "We collect the data you voluntarily provide when you contact us or request a project, and limited technical data generated by your use of the site.",
        ],
        list: [
          "Identification and contact data: name, email address, phone number and company you provide via WhatsApp, email or contact forms.",
          "Project data: the details you share about your operation, product or idea so we can scope a proposal.",
          "Technical and usage data: IP address, device and browser type, pages visited and general analytics events, collected through cookies and similar technologies.",
        ],
      },
      {
        heading: "3. Purposes of processing",
        paragraphs: ["We process personal data to:"],
        list: [
          "Respond to inquiries and prepare commercial proposals for AI systems, connected products and custom production.",
          "Manage the commercial and contractual relationship with clients and prospects.",
          "Improve the site, measure performance and understand how visitors use it.",
          "Comply with legal, accounting and tax obligations applicable in Colombia.",
        ],
      },
      {
        heading: "4. Legal basis and authorization",
        paragraphs: [
          "We process your personal data based on the authorization you give us when you submit a form, start a WhatsApp conversation or otherwise voluntarily share your information with us, in accordance with Article 9 of Law 1581 of 2012. You may withdraw this authorization at any time as described in Section 6 below.",
        ],
      },
      {
        heading: "5. Who we share data with",
        paragraphs: [
          "We do not sell personal data. We may share limited data with service providers strictly to operate the site and our commercial channels — for example, hosting infrastructure, WhatsApp Business, analytics and email tools — under confidentiality obligations, and only to the extent necessary for those services. We may also disclose data when required by a Colombian judicial or administrative authority.",
        ],
      },
      {
        heading: "6. Your rights as data owner",
        paragraphs: [
          "As established by Article 8 of Law 1581 of 2012, you have the right to:",
        ],
        list: [
          "Know, update and rectify your personal data.",
          "Request proof of the authorization granted to Colosson, except when it is not required by law.",
          "Be informed, upon request, about the use given to your data.",
          "Request the deletion of your data or revoke your authorization when the treatment does not respect legal or constitutional principles.",
          "Access your personal data free of charge.",
          "File complaints with the Superintendencia de Industria y Comercio (SIC) once you have exhausted the consultation or claim process with Colosson.",
        ],
      },
      {
        heading: "7. How to exercise your rights",
        paragraphs: [
          "You can submit consultations, updates, corrections, deletion requests or revoke your authorization by writing to ventas@colosson.co. We will respond to consultations within a maximum of ten (10) business days and to claims within a maximum of fifteen (15) business days, extendable as permitted by law, notifying you if an extension is required.",
        ],
      },
      {
        heading: "8. Data security",
        paragraphs: [
          "We apply reasonable technical, administrative and organizational measures to protect personal data against loss, unauthorized access, alteration or misuse, proportionate to the sensitivity of the data we handle:",
        ],
        list: [
          "Encryption in transit: all traffic to and from colosson.net and our commercial channels travels over encrypted connections (HTTPS/TLS).",
          "Encryption and safeguards at rest: data stored with our hosting and infrastructure providers is kept behind access controls and, where the provider supports it, encrypted at rest.",
          "Restricted access: only Colosson personnel who need the data to fulfill the purposes described in Section 3 can access it, under confidentiality obligations.",
          "Sensitive data: Colosson does not request or require sensitive personal data (health, biometric data, racial or ethnic origin, sexual orientation, political opinions, religious or union membership, or other categories defined in Article 5 of Law 1581 of 2012) to provide its services. If we inadvertently receive such data, we apply reinforced protection measures under Article 6 of Law 1581 of 2012 and delete or anonymize it as soon as reasonably possible, unless you have given express authorization for a specific purpose.",
          "Retention: we keep personal data only for as long as needed to fulfill the purposes described in this policy or as required by law, after which it is deleted or securely anonymized.",
        ],
      },
      {
        heading: "9. Cookies and similar technologies",
        paragraphs: [
          "The site uses cookies and analytics tools to understand traffic and improve the experience. You can control cookies through your browser settings; disabling them may affect some site functionality.",
        ],
      },
      {
        heading: "10. Data of minors",
        paragraphs: [
          "Our services are directed at businesses and professionals. We do not knowingly collect personal data from minors. If you believe a minor has provided us with personal data, please contact us so we can delete it.",
        ],
      },
      {
        heading: "11. International transfers",
        paragraphs: [
          "Some of the technology providers we use to operate this site (such as hosting or analytics infrastructure) may process data outside Colombia. In those cases, we take reasonable steps to ensure an adequate level of protection consistent with Colombian data protection law.",
        ],
      },
      {
        heading: "12. Changes to this policy",
        paragraphs: [
          "We may update this policy to reflect operational or legal changes. Material changes will be published on this page with an updated revision date.",
        ],
      },
    ],
    back: "Back to Colosson",
    contactLabel: "Questions about your data",
  },
  es: {
    metaTitle: "Política de privacidad | Colosson",
    metaDescription:
      "Cómo Colosson recolecta, usa y protege los datos personales conforme a la Ley 1581 de 2012 y el Decreto 1074 de 2015 en Colombia.",
    kicker: "Legal · Protección de datos",
    title: "Política de privacidad",
    updated: "Última actualización: 3 de septiembre de 2026",
    intro:
      "Esta política explica cómo Colosson S.A.S. (“Colosson”, “nosotros”) recolecta, usa, almacena y protege los datos personales de visitantes, clientes y prospectos, de acuerdo con la Ley 1581 de 2012, el Decreto 1074 de 2015 (Título 2, Capítulo 25) y los lineamientos de la Superintendencia de Industria y Comercio (SIC), autoridad colombiana de protección de datos.",
    sections: [
      {
        heading: "1. Responsable del tratamiento",
        paragraphs: [
          "Colosson S.A.S., con domicilio en Medellín, Antioquia, Colombia, es el Responsable del Tratamiento de los datos personales recolectados a través de colosson.net y nuestros canales comerciales.",
          "Contacto: ventas@colosson.co · +57 317 089 3000 · Medellín, Colombia.",
        ],
      },
      {
        heading: "2. Datos que recolectamos",
        paragraphs: [
          "Recolectamos los datos que usted proporciona voluntariamente al contactarnos o solicitar un proyecto, y datos técnicos limitados generados por el uso del sitio.",
        ],
        list: [
          "Datos de identificación y contacto: nombre, correo electrónico, teléfono y empresa que usted comparte por WhatsApp, correo o formularios de contacto.",
          "Datos del proyecto: la información que comparte sobre su operación, producto o idea para que podamos preparar una propuesta.",
          "Datos técnicos y de navegación: dirección IP, tipo de dispositivo y navegador, páginas visitadas y eventos analíticos generales, recolectados mediante cookies y tecnologías similares.",
        ],
      },
      {
        heading: "3. Finalidades del tratamiento",
        paragraphs: ["Tratamos los datos personales para:"],
        list: [
          "Responder consultas y preparar propuestas comerciales de sistemas de IA, productos conectados y producción personalizada.",
          "Gestionar la relación comercial y contractual con clientes y prospectos.",
          "Mejorar el sitio, medir su desempeño y entender cómo lo usan los visitantes.",
          "Cumplir obligaciones legales, contables y tributarias aplicables en Colombia.",
        ],
      },
      {
        heading: "4. Base legal y autorización",
        paragraphs: [
          "Tratamos sus datos personales con base en la autorización que usted otorga al diligenciar un formulario, iniciar una conversación por WhatsApp o compartir voluntariamente su información con nosotros, conforme al artículo 9 de la Ley 1581 de 2012. Usted puede revocar esta autorización en cualquier momento, como se describe en la sección 6.",
        ],
      },
      {
        heading: "5. Con quién compartimos datos",
        paragraphs: [
          "No vendemos datos personales. Podemos compartir datos limitados con proveedores de servicios estrictamente para operar el sitio y nuestros canales comerciales — por ejemplo, infraestructura de hosting, WhatsApp Business, herramientas de analítica y correo — bajo obligaciones de confidencialidad y solo en la medida necesaria para dichos servicios. También podemos divulgar datos cuando lo exija una autoridad judicial o administrativa colombiana.",
        ],
      },
      {
        heading: "6. Sus derechos como titular",
        paragraphs: [
          "Conforme al artículo 8 de la Ley 1581 de 2012, usted tiene derecho a:",
        ],
        list: [
          "Conocer, actualizar y rectificar sus datos personales.",
          "Solicitar prueba de la autorización otorgada a Colosson, salvo que la ley no lo exija.",
          "Ser informado, previa solicitud, sobre el uso dado a sus datos.",
          "Solicitar la supresión de sus datos o revocar su autorización cuando el tratamiento no respete los principios legales o constitucionales.",
          "Acceder de forma gratuita a sus datos personales.",
          "Presentar quejas ante la Superintendencia de Industria y Comercio (SIC) una vez agotado el trámite de consulta o reclamo ante Colosson.",
        ],
      },
      {
        heading: "7. Cómo ejercer sus derechos",
        paragraphs: [
          "Puede presentar consultas, actualizaciones, correcciones, solicitudes de supresión o revocar su autorización escribiendo a ventas@colosson.co. Responderemos las consultas en un máximo de diez (10) días hábiles y los reclamos en un máximo de quince (15) días hábiles, prorrogable conforme a la ley, informándole si se requiere una prórroga.",
        ],
      },
      {
        heading: "8. Seguridad de la información",
        paragraphs: [
          "Aplicamos medidas técnicas, administrativas y organizacionales razonables para proteger los datos personales frente a pérdida, acceso no autorizado, alteración o uso indebido, proporcionales a la sensibilidad de los datos que manejamos:",
        ],
        list: [
          "Cifrado en tránsito: todo el tráfico hacia y desde colosson.net y nuestros canales comerciales viaja mediante conexiones cifradas (HTTPS/TLS).",
          "Cifrado y resguardo en reposo: los datos almacenados con nuestros proveedores de hosting e infraestructura se mantienen bajo controles de acceso y, cuando el proveedor lo soporta, cifrados en reposo.",
          "Acceso restringido: solo el personal de Colosson que necesita los datos para cumplir las finalidades descritas en la sección 3 puede acceder a ellos, bajo obligaciones de confidencialidad.",
          "Datos sensibles: Colosson no solicita ni requiere datos personales sensibles (salud, datos biométricos, origen racial o étnico, orientación sexual, opiniones políticas, convicciones religiosas o afiliación sindical, u otras categorías definidas en el artículo 5 de la Ley 1581 de 2012) para prestar sus servicios. Si llegamos a recibir este tipo de datos de forma inadvertida, aplicamos medidas de protección reforzadas conforme al artículo 6 de la Ley 1581 de 2012 y los eliminamos o anonimizamos tan pronto como sea razonablemente posible, salvo que usted otorgue autorización expresa para un fin específico.",
          "Retención: conservamos los datos personales solo durante el tiempo necesario para cumplir las finalidades descritas en esta política o los plazos exigidos por la ley, y luego los eliminamos o anonimizamos de forma segura.",
        ],
      },
      {
        heading: "9. Cookies y tecnologías similares",
        paragraphs: [
          "El sitio usa cookies y herramientas analíticas para entender el tráfico y mejorar la experiencia. Usted puede controlar las cookies desde la configuración de su navegador; deshabilitarlas puede afectar algunas funciones del sitio.",
        ],
      },
      {
        heading: "10. Datos de menores de edad",
        paragraphs: [
          "Nuestros servicios están dirigidos a empresas y profesionales. No recolectamos deliberadamente datos personales de menores de edad. Si considera que un menor nos ha proporcionado datos personales, contáctenos para eliminarlos.",
        ],
      },
      {
        heading: "11. Transferencias internacionales",
        paragraphs: [
          "Algunos proveedores tecnológicos que usamos para operar este sitio (como infraestructura de hosting o analítica) pueden tratar datos fuera de Colombia. En esos casos, tomamos medidas razonables para garantizar un nivel de protección adecuado, conforme a la normativa colombiana de protección de datos.",
        ],
      },
      {
        heading: "12. Cambios a esta política",
        paragraphs: [
          "Podemos actualizar esta política para reflejar cambios operativos o legales. Los cambios sustanciales se publicarán en esta página con una fecha de actualización.",
        ],
      },
    ],
    back: "Volver a Colosson",
    contactLabel: "Preguntas sobre sus datos",
  },
};

export const termsOfService: Record<Language, LegalCopy> = {
  en: {
    metaTitle: "Terms of Service | Colosson",
    metaDescription:
      "Terms governing the use of colosson.net and Colosson's commercial services, under Colombian law (Law 1480 of 2011 and Law 527 of 1999).",
    kicker: "Legal · Terms",
    title: "Terms of service",
    updated: "Last updated: September 3, 2026",
    intro:
      "These terms govern the use of colosson.net and the commercial relationship between Colosson S.A.S. (“Colosson”, “we”) and anyone who visits the site or requests our services (“you”, “the client”). By using this site or contacting us to start a project, you accept these terms, which are governed by Colombian law, including Law 1480 of 2011 (Consumer Protection Statute) and Law 527 of 1999 on electronic commerce.",
    sections: [
      {
        heading: "1. Who we are",
        paragraphs: [
          "Colosson S.A.S. is a technology company based in Medellín, Colombia, operating under two areas: Colosson AI (AI systems, automation and digital products) and Colosson 3D (custom 3D-printed products and connected/NFC hardware). Contact: ventas@colosson.co · +57 317 089 3000.",
        ],
      },
      {
        heading: "2. Scope of the services",
        paragraphs: [
          "Colosson offers custom technology and production services — not off-the-shelf products sold through an online store. Every project (AI systems, connected products, custom manufacturing) is scoped, quoted and agreed individually with the client before work begins. This site is informational and serves to present our work and start that conversation; it does not constitute an automatic purchase or subscription process.",
        ],
      },
      {
        heading: "3. Acceptable use of the site",
        paragraphs: ["When using colosson.net you agree to:"],
        list: [
          "Provide truthful information when contacting us or requesting a proposal.",
          "Not use the site for unlawful purposes or to attempt to compromise its security or availability.",
          "Not reproduce, resell or exploit the site's content without our prior written consent.",
        ],
      },
      {
        heading: "4. Quotes, contracting and payment",
        paragraphs: [
          "Any commercial proposal, timeline, price or scope shared through WhatsApp, email or a formal quote is only binding once both parties confirm it in writing (for example, an accepted proposal, purchase order or signed agreement). Specific payment terms, delivery timelines and deliverables are defined per project in that agreement, not on this site.",
        ],
      },
      {
        heading: "5. Intellectual property",
        paragraphs: [
          "The content of this site — including text, images, the Colosson brand, logos and the design of products shown in our portfolio — is owned by Colosson or used with authorization, and is protected under Colombian intellectual property law. Unless otherwise agreed in writing, ownership of intellectual property created for a specific client project is defined in that project's agreement.",
        ],
      },
      {
        heading: "6. Third-party channels",
        paragraphs: [
          "This site links to third-party channels such as WhatsApp for direct communication. Your use of those channels is also subject to their own terms and privacy practices, which Colosson does not control.",
        ],
      },
      {
        heading: "7. Limitation of liability",
        paragraphs: [
          "The site and its general content are provided “as is” for informational purposes. Colosson is not liable for indirect damages arising from the use of the site itself; liability related to a contracted project is governed by the specific agreement for that project and applicable Colombian law.",
        ],
      },
      {
        heading: "8. Personal data",
        paragraphs: [
          "Personal data shared through this site or our commercial channels is handled according to our Privacy Policy, available on this site, in line with Law 1581 of 2012 and Decree 1074 of 2015.",
        ],
      },
      {
        heading: "9. Governing law and jurisdiction",
        paragraphs: [
          "These terms are governed by the laws of the Republic of Colombia. Any dispute arising from the use of the site or these terms will be submitted to the competent authorities in Medellín, Colombia, without prejudice to any consumer-protection venue you may be entitled to under Law 1480 of 2011.",
        ],
      },
      {
        heading: "10. Changes to these terms",
        paragraphs: [
          "We may update these terms to reflect operational or legal changes. Material changes will be published on this page with an updated revision date.",
        ],
      },
    ],
    back: "Back to Colosson",
    contactLabel: "Questions about these terms",
  },
  es: {
    metaTitle: "Términos y condiciones | Colosson",
    metaDescription:
      "Términos que rigen el uso de colosson.net y los servicios comerciales de Colosson, conforme a la Ley 1480 de 2011 y la Ley 527 de 1999.",
    kicker: "Legal · Términos",
    title: "Términos y condiciones",
    updated: "Última actualización: 3 de septiembre de 2026",
    intro:
      "Estos términos rigen el uso de colosson.net y la relación comercial entre Colosson S.A.S. (“Colosson”, “nosotros”) y cualquier persona que visite el sitio o solicite nuestros servicios (“usted”, “el cliente”). Al usar este sitio o contactarnos para iniciar un proyecto, usted acepta estos términos, regidos por la ley colombiana, incluyendo la Ley 1480 de 2011 (Estatuto del Consumidor) y la Ley 527 de 1999 sobre comercio electrónico.",
    sections: [
      {
        heading: "1. Quiénes somos",
        paragraphs: [
          "Colosson S.A.S. es una empresa de tecnología con sede en Medellín, Colombia, que opera bajo dos frentes: Colosson AI (sistemas de IA, automatización y productos digitales) y Colosson 3D (productos personalizados impresos en 3D y hardware conectado/NFC). Contacto: ventas@colosson.co · +57 317 089 3000.",
        ],
      },
      {
        heading: "2. Alcance de los servicios",
        paragraphs: [
          "Colosson ofrece servicios de tecnología y producción a la medida — no productos estándar vendidos a través de una tienda en línea. Cada proyecto (sistemas de IA, productos conectados, manufactura personalizada) se define, cotiza y acuerda individualmente con el cliente antes de iniciar el trabajo. Este sitio tiene fines informativos y sirve para presentar nuestro trabajo e iniciar esa conversación; no constituye un proceso automático de compra o suscripción.",
        ],
      },
      {
        heading: "3. Uso aceptable del sitio",
        paragraphs: ["Al usar colosson.net usted se compromete a:"],
        list: [
          "Proporcionar información veraz al contactarnos o solicitar una propuesta.",
          "No usar el sitio con fines ilícitos ni intentar comprometer su seguridad o disponibilidad.",
          "No reproducir, revender ni explotar el contenido del sitio sin nuestro consentimiento previo y por escrito.",
        ],
      },
      {
        heading: "4. Cotizaciones, contratación y pago",
        paragraphs: [
          "Cualquier propuesta comercial, cronograma, precio o alcance compartido por WhatsApp, correo o una cotización formal solo es vinculante una vez ambas partes lo confirmen por escrito (por ejemplo, una propuesta aceptada, una orden de compra o un contrato firmado). Las condiciones específicas de pago, los plazos de entrega y los entregables se definen por proyecto en dicho acuerdo, no en este sitio.",
        ],
      },
      {
        heading: "5. Propiedad intelectual",
        paragraphs: [
          "El contenido de este sitio — incluyendo textos, imágenes, la marca Colosson, logotipos y el diseño de los productos exhibidos en nuestro portafolio — es propiedad de Colosson o se usa con autorización, y está protegido por la normativa colombiana de propiedad intelectual. Salvo acuerdo escrito en contrario, la titularidad de la propiedad intelectual creada para el proyecto de un cliente específico se define en el contrato de ese proyecto.",
        ],
      },
      {
        heading: "6. Canales de terceros",
        paragraphs: [
          "Este sitio enlaza a canales de terceros como WhatsApp para comunicación directa. El uso de dichos canales también está sujeto a sus propios términos y prácticas de privacidad, que Colosson no controla.",
        ],
      },
      {
        heading: "7. Limitación de responsabilidad",
        paragraphs: [
          "El sitio y su contenido general se ofrecen “tal cual” con fines informativos. Colosson no es responsable por daños indirectos derivados del uso del sitio en sí; la responsabilidad relacionada con un proyecto contratado se rige por el contrato específico de ese proyecto y la ley colombiana aplicable.",
        ],
      },
      {
        heading: "8. Datos personales",
        paragraphs: [
          "Los datos personales compartidos a través de este sitio o de nuestros canales comerciales se tratan conforme a nuestra Política de Privacidad, disponible en este sitio, en línea con la Ley 1581 de 2012 y el Decreto 1074 de 2015.",
        ],
      },
      {
        heading: "9. Ley aplicable y jurisdicción",
        paragraphs: [
          "Estos términos se rigen por las leyes de la República de Colombia. Cualquier controversia derivada del uso del sitio o de estos términos se someterá a las autoridades competentes en Medellín, Colombia, sin perjuicio del fuero de protección al consumidor que le corresponda conforme a la Ley 1480 de 2011.",
        ],
      },
      {
        heading: "10. Cambios a estos términos",
        paragraphs: [
          "Podemos actualizar estos términos para reflejar cambios operativos o legales. Los cambios sustanciales se publicarán en esta página con una fecha de actualización.",
        ],
      },
    ],
    back: "Volver a Colosson",
    contactLabel: "Preguntas sobre estos términos",
  },
};
